<a href="https://colab.research.google.com/github/changhoon0807/python101/blob/main/1_1_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 주피터 노트북

## 셀 타입

- 코드
- 마크다운/텍스트

## 셀 모드

- 편집
- 명령


## 셀 실행

- Shift + Enter 현재 셀 실행하고 아래 셀 선택
- Ctrl + Enter 현재 셀 실행하고 현재 셀 선택
- Alt + Enter (colab) 현재 셀 실행하고 아래에 새로운 코드 셀 생성

## 단축키
- 구글 코랩에서는 노트북 단축키를 사용자가 지정할 수 있으며, 일반적인 주피터노트북과 달리 셀 편집모드에서도 단축키를 통해 셀 잘라내기, 새로운 셀 생성 등 셀 편집이 가능

- '메뉴-도구-단축키'에서 설정
    - 셀 잘라내기 Ctrl + m, x
    - 셀 복사하기 Ctrl + m, c
    - 셀 붙이기 Ctrl + v
    - 셀 삭제 Ctrl + m, d
    - 위에 새로운 셀 삽입하기 Ctrl + m, a
    - 아래에 새로운 셀 삽입하기 Ctrl + m, b
    - 셀 타입 코드로 변환 Ctrl + m, y
    - 셀 타입 마크다운으로 변환 Ctrl + m, m
    - 실행 취소 Ctrl + m, z
    - 단축키 확인 Ctrl + m, x
    - 선택된 여러 셀 병합 Ctrl + Shift + m
    - 현재 커서 위치에서 셀 분할 Ctrl + m, -
    - 주석 설정/해제 Ctrl + /

# 기본 자료형

## 기본 자료형에는 숫자형(정수형(int), 부동소수점형(float)), 참/거짓(bool), 문자열(str) 등이 있음

In [13]:
1

1

In [14]:
type(1)

int

In [16]:
type(1.0)

float

In [12]:
False, True # 불리언 자료형

(False, True)

In [17]:
type(False)

bool

In [18]:
type('python') # 작은 따옴표

str

In [19]:
type("python") # 큰 따옴표

str

In [ ]:
type('a')

In [ ]:
type("p")

In [20]:
type('python'), type(.5)

(str, float)

In [21]:
a = 5
b = (a == 5)
print(b)

True


In [22]:
a = 5
b = (a == 3) # equality operator
c = 'KOR'
print(a, b, c)

5 False KOR


- 더하기

In [23]:
4 + 5

9

In [24]:
'KOR' + '15' # 문자열 더하기

'KOR15'

In [25]:
'KOR' + 15

TypeError: ignored

- 수는 수끼리, 문자열은 문자열끼리 더할 수 있음
- 자료형 변경은 str(), float(), int() 등을 이용

In [26]:
'KOR' + str(15)

'KOR15'

In [27]:
type(str(15))

str

In [28]:
float(str(15))

15.0

- bool 자료형에 사칙연산을 적용할 경우 False는 0, True는 1의 값을 갖는 것으로 처리됨

In [29]:
4 + True

5

In [30]:
4 + False

4

In [31]:
4 * True

4

In [32]:
4 * False

0

In [33]:
int(True)

1

- 문자열 포맷 f-string

In [34]:
a = 2
b = 'two'
print(a, b)

2 two


In [36]:
print(f'{a} is {b}')

2 is two


In [ ]:
print(f'{a} is {b}')

In [38]:
print(f'{a:.10f} is {b}')

2.0000000000 is two


In [ ]:
print(f'{a:.2f} is {b:}')

In [ ]:
print(f'{b} is {a:.2f}')

In [ ]:
print(f'{b} is not {10000:,.2f}') # 천단위로 , 찍기

In [41]:
print(f'{b} is not {10000:,.2f}')

two is not 10,000.00


In [ ]:
print(f'1000000:,.2f')

- 문자열에서 공백 없애기: strip(), lstrip(), rstrip()

In [43]:
" abc  "

' abc  '

In [44]:
" abc ".lstrip()

'abc '

In [45]:
" abc ".rstrip()

' abc'

In [46]:
" abc ".strip()

'abc'

In [48]:
"abc".strip('bc')

'a'

# 기본 자료형 외 자주 사용되는 자료형: 리스트(list), 딕셔너리(dict), 튜플(tuple)
## 리스트
- 대괄호 [ ]로 표현하며 시퀀스 형태로 입력

In [60]:
a = [1, 2, 3]
b = ['one', 'two', 'three']
a

[1, 2, 3]

In [50]:
type(a), type(b)

(list, list)

In [51]:
a * 2 # matlab과 같은 결과를 얻으려면 list comprehension 또는 numpy 라이브러리 필요

[1, 2, 3, 1, 2, 3]

In [59]:
import numpy as np
a = np.array([1, 2, 3])
a * 2

array([2, 4, 6])

In [62]:
b * 3

['one', 'two', 'three', 'one', 'two', 'three', 'one', 'two', 'three']

In [63]:
a + b

[1, 2, 3, 'one', 'two', 'three']

In [64]:
a + 5

TypeError: ignored

In [65]:
a + 'four'

TypeError: ignored

- list에 숫자 또는 문자열을 더하는 연산이 정의되어 있지 않으므로 오류발생

In [66]:
a + [5]

[1, 2, 3, 5]

In [67]:
b + ['four']

['one', 'two', 'three', 'four']

In [68]:
b.append('four')
print(b)

['one', 'two', 'three', 'four']


- 숫자로 이루어진 리스트의 각 항목에 숫자를 더하기 위해서는 list comprehension이나 for-loop 이용

In [73]:
[i + 2 for i in a]

[3, 4, 5]

In [72]:
[i + 1 for i in a]

[2, 3, 4]

- 뒤에 다룰 넘파이 ndarray 자료형은 숫자형 자료 리스트처럼 생겼으나, 숫자 하나를 더할 수 있음

In [74]:
range(10)

range(0, 10)

In [78]:
list(range(10))[0]

0

- 리스트에 있는 문자열을 특정 기호로 연결

In [79]:
b

['one', 'two', 'three', 'four']

In [80]:
':'.join(b)

'one:two:three:four'

In [ ]:
':'.join(b)

- 파이썬 인덱스는 0부터 시작하는 것에 유의

In [82]:
a

[1, 2, 3]

In [84]:
a[0:2] # [포함:미포함]

1

In [86]:
a[0:3] # 첫번째 인덱스는 포함, 두번째 인덱스는 미포함

[1, 2, 3]

- list의 마지막 항목의 인덱스는 -1

In [87]:
a[-1]

3

In [ ]:
a[-1]

In [93]:
a = ['KOR', 'USA', 'CHN']
print(a[0])
print(a[-1])
print(a[0:2])
print(a[-2:])
#print(a[0], a[-1], a[:2], a[-2:])

KOR
CHN
['KOR', 'USA']
['USA', 'CHN']


- 주피터노트북에서 긴 리스트는 세로로 표시되지만, %pprint 명령어로 옵션 변경 가능,
- print() 명령어를 사용하면, 긴 리스트도 가로로 표시

In [94]:
a * 4

['KOR',
 'USA',
 'CHN',
 'KOR',
 'USA',
 'CHN',
 'KOR',
 'USA',
 'CHN',
 'KOR',
 'USA',
 'CHN']

In [95]:
print(a * 4)

['KOR', 'USA', 'CHN', 'KOR', 'USA', 'CHN', 'KOR', 'USA', 'CHN', 'KOR', 'USA', 'CHN']


In [96]:
from pprint import pprint

In [97]:
%pprint

Pretty printing has been turned OFF


In [99]:
a * 4

['KOR', 'USA', 'CHN', 'KOR', 'USA', 'CHN', 'KOR', 'USA', 'CHN', 'KOR', 'USA', 'CHN']

- 문자열 리스트의 각 항목을 따옴표 없이 print()하기 위해 리스트이름 앞에 * 입력
- print()가 출력하는 각 항목 사이를 구분하기 위해 sep = '기호'를 지정
- print()가 마지막에 출력할 내용을 지정하기 위해 end = '기호'를 지정(기본은 '\n')

In [100]:
print(a)

['KOR', 'USA', 'CHN']


In [101]:
print(*a)

KOR USA CHN


In [102]:
print(*a, sep = ', ')

KOR, USA, CHN


In [ ]:
print(*a, sep = ', ')

- list comprehension: for-loop 구문 한줄로 간단하게 표현하는 방법

In [104]:
['KOR', 'USA', 'CHN'] - ['CHN', 'AUS'] # output이 KOR, USA가 되도록

TypeError: ignored

In [106]:
[s for s in ['KOR', 'USA', 'CHN' ] if s not in ['CHN', 'AUS']]

['KOR', 'USA']

In [ ]:
[s for s in ['KOR', 'USA', 'CHN' ]if s not in ['CHN', 'AUS']]

- set() 이용

In [107]:
set(['KOR', 'USA', 'CHN']), set(['CHN', 'AUS'])

({'CHN', 'KOR', 'USA'}, {'CHN', 'AUS'})

In [110]:
list(set(['KOR', 'USA', 'CHN']) - set(['CHN', 'AUS']))

<class 'list'>

In [111]:
list(set(['KOR', 'USA', 'CHN']) - set(['CHN', 'AUS']))

['KOR', 'USA']

- 문자열 리스트 항목별로 문자열 더하기

In [112]:
[s + ':g' for s in ['KOR', 'USA', 'CHN']]

['KOR:g', 'USA:g', 'CHN:g']

- 문자열은 각 캐릭터(123.../abc.../가나다... 등)로 구성된 리스트로 취급

In [114]:
a = 'abcde'
a

'abcde'

In [115]:
a[:3]

'abc'

In [116]:
a[-2:]

'de'

In [117]:
"가나다라마"[:2]

'가나'

- 이전 실행한 출력셀의 값 불러오기

In [118]:
_

'가나'

In [120]:
Out[117]

'가나'

In [124]:
_

'one:two:three:four'

- range()로 수 리스트 만들기
    - range(s, e, i): 처음 위치(생략시 0), 마지막 위치(리스트에 포함 안됨), 수 간격(생략시 1)
    - for-loop 등에서 주로 이용하며, 순서대로 해당하는 값만 필요하므로 실제 리스트를 생성하지 않음
        - 리스트 생성시 메모리 공간을 크게 차지할 수 있으므로 비효율적임
    - 리스트를 생성하기 위해서는 list() 함수 실행

In [127]:
list(range(1, 10, 1))

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [128]:
for i in range(5):
    print(i)

0
1
2
3
4


In [ ]:
for i in range(5):  # range(0, 5, 1)
    print(i)

In [129]:
for i in range(5, 0, -2):
    print(i)

5
3
1


In [ ]:
list(range(10))

## 딕셔너리: key와 value로 구성되며, { }로 표현

In [130]:
[1, 2, 3]

[1, 2, 3]

In [131]:
{'a': 1, 'b': 2}

{'a': 1, 'b': 2}

In [132]:
iso = {'US':'USA', 'KR':'KOR', 'JP':'JPN', 'CN':'CHN'}

In [133]:
kr_en = {'서울특별시':'SE', '경기도':'GG', '인천광역시':'IC'}

In [136]:
iso['KR']

'KOR'

In [ ]:
iso['KR']

In [137]:
iso.keys()

dict_keys(['US', 'KR', 'JP', 'CN'])

In [138]:
iso.values()

dict_values(['USA', 'KOR', 'JPN', 'CHN'])

In [139]:
iso['AU'] = 'AUS' # 딕셔너리에 추가

In [140]:
iso

{'US': 'USA', 'KR': 'KOR', 'JP': 'JPN', 'CN': 'CHN', 'AU': 'AUS'}

- dict, zip으로 딕셔너리 만들기

In [ ]:
zip(a, b)

In [141]:
dict(zip(['한국', '미국', '일본'], ['KR', 'US', 'JP']))

{'한국': 'KR', '미국': 'US', '일본': 'JP'}

- key 이름 바꾸기: 딕셔너리 컴프리헨션

In [142]:
{f'new_{key}':x for key, x in dict(zip(['한국', '미국', '일본'], ['KR', 'US', 'JP'])).items()}

{'new_한국': 'KR', 'new_미국': 'US', 'new_일본': 'JP'}

In [143]:
import pandas as pd
countries = pd.Series(['South Korea', 'United States', 'North Korea'])
print(countries)

0      South Korea
1    United States
2      North Korea
dtype: object


In [144]:
cdict = {'South Korea':'KR', 'United States':'US', 'Japan':'JP'}
countries.replace(cdict)

0             KR
1             US
2    North Korea
dtype: object

### 튜플: 리스트와 유사하나 값이 불변하는 특성 ( )로 표현

In [146]:
a = (1, 2, 3)

In [148]:
my_tuple = (1, 2, 'hello', [1, 2, 3])
my_tuple[0] = 3

TypeError: ignored

In [149]:
my_list = [1 ,2 ,3 ,4, 5]
my_list[0] = 2
my_list

[2, 2, 3, 4, 5]

In [150]:
a = 5, 10

In [151]:
type(a)

<class 'tuple'>

In [152]:
a, b, c = 5, 10, 15

In [153]:
print(a, b, c)

5 10 15


In [154]:
a, b = b, a
print(a, b)

10 5


In [ ]:
c = 1, 2, 3
print(type(c))

<class 'tuple'>


In [ ]:
c

(1, 2, 3)

In [165]:
np.array([1,2,3])

array([1, 2, 3])

In [167]:
import numpy as np
from numpy import array

array([1,2,3])

array([1, 2, 3])

### method

In [162]:
['1', '2', '3'][0].isnumeric()

True

In [157]:
dir(a[0])

['__add__', '__class__', '__contains__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getnewargs__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__mod__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__rmod__', '__rmul__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', 'capitalize', 'casefold', 'center', 'count', 'encode', 'endswith', 'expandtabs', 'find', 'format', 'format_map', 'index', 'isalnum', 'isalpha', 'isascii', 'isdecimal', 'isdigit', 'isidentifier', 'islower', 'isnumeric', 'isprintable', 'isspace', 'istitle', 'isupper', 'join', 'ljust', 'lower', 'lstrip', 'maketrans', 'partition', 'removeprefix', 'removesuffix', 'replace', 'rfind', 'rindex', 'rjust', 'rpartition', 'rsplit', 'rstrip', 'split', 'splitlines', 'startswith', 'strip', 'swapcase', 'title', 'translate', 'upper', 'zfill']

In [161]:
a[0].isnumeric()

True

## 연습문제

- 아래 국가명 리스트와 연도 리스트를 이용하여 국가명_연도 문자열로 구성된 리스트를 생성 (힌트, 리스트 컴프리헨션, f-string)
- 아래 리스트와 인덱스를 이용하여 일본과 중국을 제외한 국가에 대해서만 국가명_연도 문자열 리스트를 생성하라

In [169]:
countries = ['KOR', 'USA', 'JPN', 'CHN', 'AUS', 'MEX']
year = [17, 18, 19, 20]

In [170]:
[f'{c}_{y}' for c in countries for y in year]

['KOR_17', 'KOR_18', 'KOR_19', 'KOR_20', 'USA_17', 'USA_18', 'USA_19', 'USA_20', 'JPN_17', 'JPN_18', 'JPN_19', 'JPN_20', 'CHN_17', 'CHN_18', 'CHN_19', 'CHN_20', 'AUS_17', 'AUS_18', 'AUS_19', 'AUS_20', 'MEX_17', 'MEX_18', 'MEX_19', 'MEX_20']

In [171]:
[f'{c}_{y}' for c in countries if c not in ['CHN', 'JPN'] for y in year]

['KOR_17', 'KOR_18', 'KOR_19', 'KOR_20', 'USA_17', 'USA_18', 'USA_19', 'USA_20', 'AUS_17', 'AUS_18', 'AUS_19', 'AUS_20', 'MEX_17', 'MEX_18', 'MEX_19', 'MEX_20']

- 아래 문자열 리스트에서 숫자를 나타내는 문자열만 선택하여 리스트를 생성하라(힌트, isnumeric() 또는 isdigit(), strip() method 이용)

In [174]:
strings = ['KOR', '한국', ' 15', "True", '1000']

In [177]:
[n for n in strings if n.strip().isnumeric()]

[' 15', '1000']

In [ ]:
for i in a:
    dfdf

# 문법

- 파이썬에서 for loop, if 구문, 함수 정의시 indentation(스페이스 4개) 이용
    - 주피터노트북에서 tab은 스페이스 4개를 입력
- 코드작성의 자유도가 낮은 대신, 가독성이 매우 높아짐


```
<C>
if (i=1; i<=n; i++) {
  printf("%d\n", i);
}

<matlab>
for i = 1:n
    disp(i)
end

<python>
for i = range(1, n+1):
    disp(i)
```

## definition: 함수

In [178]:
def sum_two_numbers(a, b):
    return a + b

In [179]:
sum_two_numbers(1, 2)

3

In [180]:
def sum_three_numbers(a, b, c=4):
    return a + 2*b + c

In [181]:
sum_three_numbers(1, 2, 0)

5

In [182]:
sum_three_numbers(1, 2)

9

In [183]:
sum_three_numbers(b=1, a=4)

10

In [ ]:
labmda x: 표현식

In [184]:
sum_two_numbers2 = lambda x, y: x + y # lambda 함수: 간단한 한줄짜리 함수

In [185]:
sum_two_numbers2(1, 2)

3

## for-loop, if-else

In [186]:
countries = ['KOR', 'USA', 'CHN']
for c in countries:
    if c == 'KOR':
        print(c, 'is my country.')
    else:
        print(c)

KOR is my country.
USA
CHN


## enumerate: 반복 가능한 하나의 객체의 인덱스와 값 추출

In [187]:
for index, c in enumerate(countries):
    print(index, c)

0 KOR
1 USA
2 CHN


## zip: 반복가능한 객체가 2개 이상인 경우, 각 객체의 요소를 순서대로 추출

In [188]:
for i, c in zip(countries, ['한국', '미국', '중국']):
    print(i, c)

KOR 한국
USA 미국
CHN 중국


## continue, break, pass

In [189]:
for i in range(4):    # [0, 1, 2, 3]
    if i==2:
        continue
    else:
        print(f'{i} is not 2')


0 is not 2
1 is not 2
3 is not 2


In [190]:
for i in range(4):    # [0, 1, 2, 3]
    if i==2:
        break
    else:
        print(f'{i} is not 2')


0 is not 2
1 is not 2


In [194]:
A = True

if A:
    print('True')
else:
    print('False')

True


In [195]:
if A:
    pass
else:
    print('False')

## list comprehension v. for-loop
- 앞 리스트에서 뒤 리스트에 속한 항목 제외하기

In [196]:
[s for s in ['KOR', 'USA', 'CHN'] if s not in ['CHN','AUS']]

['KOR', 'USA']

In [198]:
clist = []
for c in ['KOR', 'USA', 'CHN']:
    if c not in ['CHN', 'AUS']:
        clist = clist + [c] # clist.append(c)
clist

['KOR', 'USA']

In [200]:
import numpy as np
import pandas as pd



# 라이브러리
- Numpy: 매틀랩 대체, 과학적 연산
- Pandas: 데이터 분석
- Matplotlib: 데이터 시각화, 그래프
- os, pickle: 운영체제, 시스템과 상호작용
- Statsmodels: 통계분석
- Scikit-learn, TensorFlow: 머신러닝, AI

## numpy
- ndarray는 행(row)과 열(column) 보다 첫번째 차원, 두번째 차원, 세번째 차원 등으로 정의
- 필요한 경우 matrix 자료형을 사용할 수 있으나 활용도가 낮음
- ndarray자료형을 이용하여 일반적인 matrix연산을 모두 할 수 있음
- 2-dim ndarray에서 행(row)처럼 보이는 것은 첫번째 차원임

In [201]:
import numpy # numpy 라이브러리 함수를 사용하려면 numpy. 으로 표현
import numpy as np # numpy. 에서 np. 으로 대체
print(numpy.sin(0), np.sin(0))

0.0 0.0


In [202]:
print(sin(0)) # np. 로 시작하지 않기 때문에 오류

NameError: ignored

In [203]:
print(np.pi)

3.141592653589793


## 인덱스

- 특정 열(두번째 차원)에 접근하기 위해서는 콜론(:)을 첫번째 인덱스 자리에 입력

In [262]:
a1 = np.array([[1, 2 ,3], [2, 3, 4]])

In [205]:
type(a1)

<class 'numpy.ndarray'>

In [208]:
a1

array([[1, 2, 3],
       [2, 3, 4]])

In [211]:
a1[:2, :2]

array([[1, 2],
       [2, 3]])

In [209]:
a1[:, 0] # 전체 차원의 첫번째 원소

array([1, 2])

In [210]:
a1[0, :] # 첫번째 차원의 모든 원소

array([1, 2, 3])

## 통계량 및 연산

In [212]:
v = np.array([1, 2, 3])
print(v)

[1 2 3]


In [213]:
type(v)

<class 'numpy.ndarray'>

In [214]:
m = np.array([[1, 2], [3, 4]])
m

array([[1, 2],
       [3, 4]])

In [217]:
v.mean()

2.0

In [219]:
v.std()

0.816496580927726

In [220]:
v.min()

1

In [ ]:
v.

In [ ]:
print(v.mean(), v.std(), v.max())

In [ ]:
np.sin([0, np.pi / 2, np.pi])

In [221]:
a = np.array([[1, 2], [3, 4]])

In [222]:
a

array([[1, 2],
       [3, 4]])

In [224]:
a[0,0] = -1

In [225]:
a

array([[-1,  2],
       [ 3,  4]])

In [227]:
a[0] = 0
a

array([[0, 0],
       [3, 4]])

In [229]:
a[:, 1] = [5, 6]
print(a)

[[0 5]
 [3 6]]


In [230]:
v1 = np.array([1, 2, 3])
v2 = np.array([-1, 0, 1])

In [231]:
v1 + 1

array([2, 3, 4])

In [232]:
v1 * 2

array([2, 4, 6])

In [233]:
v1 ** 2 #제곱

array([1, 4, 9])

In [234]:
v1 + v2

array([0, 2, 4])

In [235]:
np.log(v1)

array([0.        , 0.69314718, 1.09861229])

In [236]:
np.exp(v1)

array([ 2.71828183,  7.3890561 , 20.08553692])

## matrix operation

- numpy array로 생성된 객체는 ndarray 클래스의 메소드와 속성을 가짐
- transpose, dot product 등

In [260]:
a2 = np.array([[1, 2], [3, 4], [5, 6]])
a3 = np.array([[1, 2], [3, 4], [5, 6]])

In [261]:
a2.shape

(3, 2)

In [264]:
a1.shape

(2, 3)

In [265]:
a1 * a2

ValueError: ignored

In [266]:
a2 * a3

array([[ 1,  4],
       [ 9, 16],
       [25, 36]])

In [267]:
a1.dot(a2)

array([[22, 28],
       [31, 40]])

In [268]:
np.dot(a1, a2)

array([[22, 28],
       [31, 40]])

In [269]:
a1 @ a2 # 파이썬 3.5

array([[22, 28],
       [31, 40]])

In [270]:
A = np.dot(a1, a2)
print(A)

[[22 28]
 [31 40]]


- 역행렬: numpy.linalg.inv() 함수 이용

In [272]:
np.linalg.inv(a1.dot(a2))

array([[ 3.33333333, -2.33333333],
       [-2.58333333,  1.83333333]])

In [ ]:
print(np.linalg.inv(a1.dot(a2)))

In [274]:
from numpy.linalg import inv

In [275]:
inv(a1.dot(a2))

array([[ 3.33333333, -2.33333333],
       [-2.58333333,  1.83333333]])

In [276]:
inv(a1 @ a2)

array([[ 3.33333333, -2.33333333],
       [-2.58333333,  1.83333333]])

In [277]:
a1.shape[0]

2

In [278]:
np.identity(a1.shape[0])

array([[1., 0.],
       [0., 1.]])

In [279]:
from numpy import identity as eye #eye()

In [280]:
eye(a1.shape[0])

array([[1., 0.],
       [0., 1.]])

- 레온티에프 역행렬: $(I - A)^{-1}$

In [281]:
np.linalg.inv(np.identity(A.shape[0]) - A)

array([[ 0.79591837, -0.57142857],
       [-0.63265306,  0.42857143]])

In [282]:
inv(eye(A.shape[0]) - A)

array([[ 0.79591837, -0.57142857],
       [-0.63265306,  0.42857143]])

## random sample

- 동일한 랜덤표본을 얻기 위해서는 numpy.random.seed(n) (예: n=1) 실행
    - seed()를 지정하지 않는 경우 파이썬은 현재 날짜-시간을 이용하여 seed() 지정

In [ ]:
# np.random.randn(n)

In [283]:
import numpy as np

In [286]:
numpy.random.seed(1)

In [290]:
numpy.random.seed(1)
rsn = np.random.randn(10) # 표준정규분포에서 샘플링
print(rsn)

[ 1.62434536 -0.61175641 -0.52817175 -1.07296862  0.86540763 -2.3015387
  1.74481176 -0.7612069   0.3190391  -0.24937038]


In [292]:
numpy.random.seed(1)
rsn1 = np.random.normal(2, 5, 10)
print(rsn1)

[10.12172682 -1.05878207 -0.64085876 -3.36484311  6.32703815 -9.50769348
 10.72405882 -1.8060345   3.59519548  0.75314812]


In [ ]:
rsn

array([-1.18997876, -0.11208947, -0.62463444,  1.37361405,  0.12405343,
        0.18767963, -1.04043274,  0.22354029,  0.16219621, -1.75278601])

In [295]:
rsi = np.random.randint(1, 10, 10) # 1과 9사이에서 10개 샘플링

In [296]:
rsi

array([2, 1, 2, 9, 9, 4, 9, 8, 4, 7])

In [297]:
rsu = np.random.uniform(-1, 1, 10)

In [298]:
rsu

array([ 0.91577906,  0.06633057,  0.38375423, -0.36896874,  0.37300186,
        0.66925134, -0.96342345,  0.50028863,  0.97772218,  0.49633131])

In [299]:
np.random.seed(1)
np.random.randn(3)

array([ 1.62434536, -0.61175641, -0.52817175])

In [302]:
np.random.seed(1)
np.random.randn(3)

array([ 1.62434536, -0.61175641, -0.52817175])

In [303]:
np.random.seed(1)
np.random.randn(3)

array([ 1.62434536, -0.61175641, -0.52817175])

# 연습문제
1. $x + y + x*y + x ** 2$ 계산해서 return하는 함수 생성 (def)

In [310]:
def func_test(x=0, y=1):
    return x + y + x*y + x**2

func_test(x=2, y=2)

12

2. 아래 a1, a2 리스트를 이용해서 a1의 요소가 key이고, a2의 요소가 value인 딕셔너리 생성( dict(), zip() )

In [319]:
a1 = ['a', 'b', 'c', 'd', 'e']
a2 = list(range(5))

a3 = dict(zip(a1, a2))

In [313]:
a3['a']

0

3. 리스트 컴프리헨션을 이용해서 아래 a 리스트의 각 요소를 제곱한 리스트 생성

In [315]:
a = list(range(2, 10))

In [316]:
[x**2 for x in a]

[4, 9, 16, 25, 36, 49, 64, 81]

4. 위의 a 리스트를 ndarray 자료형으로 변환하고 제곱하시오

In [318]:
list(np.array(list(range(2, 10))) ** 2)

[4, 9, 16, 25, 36, 49, 64, 81]

5. 2의 a1 리스트의 인덱스와 요소를 반복구문을 통해 print하시오 ( enumerate() )

In [320]:
for ind, x in enumerate(a1):
    print(ind, x)

0 a
1 b
2 c
3 d
4 e
