<a href="https://colab.research.google.com/github/changhoon0807/python101/blob/main/1_1_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 주피터노트북


## 셀 타입

- 코드
- 마크다운/텍스트

## 셀 모드

- 편집
- 명령


## 셀 실행

- Shift + Enter 현재 셀 실행하고 아래 셀 선택
- Ctrl + Enter 현재 셀 실행하고 현재 셀 선택
- Alt + Enter (colab) 현재 셀 실행하고 아래에 새로운 코드 셀 생성

## 단축키
- 구글 코랩에서는 노트북 단축키를 사용자가 지정할 수 있으며, 일반적인 주피터노트북과 달리 셀 편집모드에서도 단축키를 통해 셀 잘라내기, 새로운 셀 생성 등 셀 편집이 가능

- '메뉴-도구-단축키'에서 설정
    - 셀 잘라내기 Ctrl + m, x
    - 셀 복사하기 Ctrl + m, c
    - 셀 붙이기 Ctrl + v
    - 셀 삭제 Ctrl + m, d
    - 위에 새로운 셀 삽입하기 Ctrl + m, a
    - 아래에 새로운 셀 삽입하기 Ctrl + m, b
    - 셀 타입 코드로 변환 Ctrl + m, y
    - 셀 타입 마크다운으로 변환 Ctrl + m, m
    - 실행 취소 Ctrl + m, z
    - 단축키 확인 Ctrl + m, x
    - 선택된 여러 셀 병합 Ctrl + Shift + m
    - 현재 커서 위치에서 셀 분할 Ctrl + m, -
    - 주석 설정/해제 Ctrl + /

# 기본 자료형

## 기본 자료형에는 숫자형(정수형(int), 부동소수점형(float)), 참/거짓(bool), 문자열(str) 등이 있음

In [ ]:
1

In [ ]:
type(1)

In [ ]:
type(1.0)

In [ ]:
False, True # 불리언 자료형

In [ ]:
type(False)

In [ ]:
type('python') # 작은 따옴표

In [ ]:
type("python") # 큰 따옴표

In [ ]:
type('a')

In [ ]:
type("p")

In [ ]:
type('python'), type(.5)

In [ ]:
a = 5
b = (a == 3) # equality operator
c = 'KOR'
print(a, b, c)

- 더하기

In [ ]:
4 + 5

In [ ]:
'KOR' + '15' # 문자열 더하기

In [ ]:
'KOR' + 15

- 수는 수끼리, 문자열은 문자열끼리 더할 수 있음
- 자료형 변경은 str(), float(), int() 등을 이용

In [ ]:
'KOR' + str(15)

In [ ]:
type(str(15))

In [ ]:
float(str(15))

- bool 자료형에 사칙연산을 적용할 경우 False는 0, True는 1의 값을 갖는 것으로 처리됨

In [ ]:
4 + True

In [ ]:
4 + False

In [ ]:
4 * True

In [ ]:
4 * False

In [ ]:
int(True)

- 문자열 포맷 f-string

In [ ]:
a = 2
b = 'two'
print(a, b)

In [ ]:
print(f'{a} is {b}')

In [ ]:
print(f'{a:.2f} is {b:}')

In [ ]:
print(f'{b} is {a:.2f}')

In [ ]:
print(f'{b} is not {10000:,.2f}') # 천단위로 , 찍기

In [ ]:
print(f'1000000:,.2f')

- 문자열에서 공백 없애기: strip(), lstrip(), rstrip()

In [ ]:
" abc ".lstrip()

In [ ]:
" abc ".rstrip()

In [ ]:
" abc ".strip()

In [ ]:
"abc".strip('a')

# 기본 자료형 외 자주 사용되는 자료형: 리스트(list), 딕셔너리(dict), 튜플(tuple)
## 리스트
- 대괄호 [ ]로 표현하며 시퀀스 형태로 입력

In [47]:
a = [1, 2, 3]
b = ['one', 'two', 'three']

In [ ]:
type(a), type(b)

In [ ]:
a * 2 # matlab과 같은 결과를 얻으려면 list comprehension 또는 numpy 라이브러리 필요

In [ ]:
b * 2

In [ ]:
a + b

In [ ]:
a + 5

In [ ]:
a + 'four'

- list에 숫자 또는 문자열을 더하는 연산이 정의되어 있지 않으므로 오류발생

In [ ]:
a + [5]

[1, 2, 3, 5]

In [ ]:
b + ['four']

In [ ]:
b.append('four')
print(b)

- 숫자로 이루어진 리스트의 각 항목에 숫자를 더하기 위해서는 list comprehension이나 for-loop 이용

In [ ]:
[i + 1 for i in a]

- 뒤에 다룰 넘파이 ndarray 자료형은 숫자형 자료 리스트처럼 생겼으나, 숫자 하나를 더할 수 있음

In [ ]:
list(range(10))

- 리스트에 있는 문자열을 특정 기호로 연결

In [ ]:
b

In [ ]:
':'.join(b)

- 파이썬 인덱스는 0부터 시작하는 것에 유의

In [ ]:
a[0]

In [ ]:
a[0:2] # 첫번째 인덱스는 포함, 두번째 인덱스는 미포함

- list의 마지막 항목의 인덱스는 -1

In [ ]:
a[-1]

In [ ]:
a = ['KOR', 'USA', 'CHN']
print(a[0], a[-1], a[:2], a[-2:])

- 주피터노트북에서 긴 리스트는 세로로 표시되지만, %pprint 명령어로 옵션 변경 가능,
- print() 명령어를 사용하면, 긴 리스트도 가로로 표시

In [ ]:
a * 4

In [ ]:
print(a * 4)

In [82]:
from pprint import pprint

In [ ]:
%pprint

In [ ]:
a * 4

- 문자열 리스트의 각 항목을 따옴표 없이 print()하기 위해 리스트이름 앞에 * 입력
- print()가 출력하는 각 항목 사이를 구분하기 위해 sep = '기호'를 지정
- print()가 마지막에 출력할 내용을 지정하기 위해 end = '기호'를 지정(기본은 '\n')

In [ ]:
print(a)

In [ ]:
print(*a)

In [ ]:
print(*a, sep = ', ')

- list comprehension

In [ ]:
['KOR', 'USA', 'CHN'] - ['CHN', 'AUS'] # output이 KOR, USA가 되도록

In [ ]:
[s for s in ['KOR', 'USA', 'CHN'] if s not in ['CHN', 'AUS']]

- set() 이용

In [ ]:
set(['KOR', 'USA', 'CHN']), set(['CHN', 'AUS'])

In [ ]:
set(['KOR', 'USA', 'CHN']) - set(['CHN', 'AUS'])

In [ ]:
list(set(['KOR', 'USA', 'CHN']) - set(['CHN', 'AUS']))

- 문자열 리스트 항목별로 문자열 더하기

In [ ]:
[s + ':g' for s in ['KOR', 'USA', 'CHN']]

- 문자열은 각 캐릭터(123.../abc.../가나다... 등)로 구성된 리스트로 취급

In [91]:
a = 'abcde'

In [92]:
a[:3]

'abc'

In [93]:
a[-2:]

'de'

In [ ]:
"가나다라마"[:2]

'가나'

- 이전 실행한 출력셀의 값 불러오기

In [ ]:
_

In [ ]:
Out[68]

In [ ]:
_68

- range()로 수 리스트 만들기
    - range(s, e, i): 처음 위치(생략시 0), 마지막 위치(리스트에 포함 안됨), 수 간격(생략시 1)
    - for-loop 등에서 주로 이용하며, 순서대로 해당하는 값만 필요하므로 실제 리스트를 생성하지 않음
        - 리스트 생성시 메모리 공간을 크게 차지할 수 있으므로 비효율적임
    - 리스트를 생성하기 위해서는 list() 함수 실행

In [ ]:
for i in range(5):  # range(0, 5, 1)
    print(i)

In [ ]:
for i in range(5, 0, -2):
    print(i)

In [ ]:
list(range(10))

## 딕셔너리: key와 value로 구성되며, { }로 표현

In [103]:
iso = {'US':'USA', 'KR':'KOR', 'JP':'JPN', 'CN':'CHN'}

In [102]:
kr_en = {'서울특별시':'SE', '경기도':'GG', '인천광역시':'IC'}

In [ ]:
iso['US']

In [ ]:
iso['KR']

In [ ]:
iso.keys()

In [ ]:
iso.values()

In [ ]:
iso['AU'] = 'AUS' # 딕셔너리에 추가

In [ ]:
iso

- dict, zip으로 딕셔너리 만들기

In [ ]:
dict(zip(['한국', '미국', '일본'], ['KR', 'US', 'JP']))

- key 이름 바꾸기: 딕셔너리 컴프리헨션

In [ ]:
{f'new_{key}':x for key, x in dict(zip(['한국', '미국', '일본'], ['KR', 'US', 'JP'])).items()}

In [ ]:
import pandas as pd
countries = pd.Series(['South Korea', 'United States', 'North Korea'])
print(countries)

In [ ]:
cdict = {'South Korea':'KR', 'United States':'US', 'Japan':'JP'}
countries.replace(cdict)

### 튜플: 리스트와 유사하나 값이 불변하는 특성 ( )로 표현

In [ ]:
my_tuple = (1, 2, 'hello', [1, 2, 3])
my_tuple[0] = 3

In [ ]:
my_list = [1 ,2 ,3 ,4, 5]
my_list[0] = 2
my_list

In [120]:
a, b, c = 5, 10, 15

In [ ]:
print(a, b, c)

In [ ]:
a, b = b, a
print(a, b)

10 5


In [125]:
c = 1, 2, 3
print(type(c))

<class 'tuple'>


In [126]:
c

(1, 2, 3)

### method

In [158]:
a = ['1', '2', '3']

In [160]:
dir(a[0])

['__add__', '__class__', '__contains__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getnewargs__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__mod__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__rmod__', '__rmul__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', 'capitalize', 'casefold', 'center', 'count', 'encode', 'endswith', 'expandtabs', 'find', 'format', 'format_map', 'index', 'isalnum', 'isalpha', 'isascii', 'isdecimal', 'isdigit', 'isidentifier', 'islower', 'isnumeric', 'isprintable', 'isspace', 'istitle', 'isupper', 'join', 'ljust', 'lower', 'lstrip', 'maketrans', 'partition', 'removeprefix', 'removesuffix', 'replace', 'rfind', 'rindex', 'rjust', 'rpartition', 'rsplit', 'rstrip', 'split', 'splitlines', 'startswith', 'strip', 'swapcase', 'title', 'translate', 'upper', 'zfill']

In [161]:
a[0].isnumeric()

True

## 연습문제

- 아래 국가명 리스트와 연도 리스트를 이용하여 국가명_연도 문자열로 구성된 리스트를 생성 (힌트, 리스트 컴프리헨션, f-string)
- 아래 리스트와 인덱스를 이용하여 일본과 중국을 제외한 국가에 대해서만 국가명_연도 문자열 리스트를 생성하라

In [131]:
countries = ['KOR', 'USA', 'JPN', 'CHN', 'AUS', 'MEX']
year = [17, 18, 19, 20]

- 아래 문자열 리스트에서 숫자를 나타내는 문자열만 선택하여 리스트를 생성하라(힌트, isnumeric() 또는 isdigit(), strip() method 이용)

In [150]:
strings = ['KOR', '한국', ' 15', "True", '1000']

# 문법

- 파이썬에서 for loop, if 구문, 함수 정의시 indentation(스페이스 4개) 이용
    - 주피터노트북에서 tab은 스페이스 4개를 입력
- 코드작성의 자유도가 낮은 대신, 가독성이 매우 높아짐


```
<C>
if (i=1; i<=n; i++) {
  printf("%d\n", i);
}

<matlab>
for i = 1:n
    disp(i)
end

<python>
for i = range(1, n+1):
    disp(i)
```

## definition: 함수

In [ ]:
def sum_two_numbers(a, b):
    return a + b

In [ ]:
sum_two_numbers(1, 2)

In [ ]:
def sum_three_numbers(a, b, c=4):
    return a + 2*b + c

In [ ]:
sum_three_numbers(1, 2, 0)

In [ ]:
sum_three_numbers(1, 2)

In [ ]:
sum_three_numbers(b=2, a=1)

In [163]:
sum_two_numbers2 = lambda x, y: x + y # lambda 함수: 간단한 한줄짜리 함수

In [ ]:
sum_two_numbers2(1, 2)

## for-loop, if-else

In [ ]:
countries = ['KOR', 'USA', 'CHN']
for c in countries:
    if c == 'KOR':
        print(c, 'is my country.')
    else:
        print(c)

## enumerate: 반복 가능한 하나의 객체의 인덱스와 값 추출

In [ ]:
for i, c in enumerate(countries):
    print(i, c)

## zip: 반복가능한 객체가 2개 이상인 경우, 각 객체의 요소를 순서대로 추출

In [ ]:
for i, c in zip(countries, ['한국', '미국', '중국']):
    print(i, c)

## continue, break, pass

In [ ]:
for i in range(4):    # [0, 1, 2, 3]
    if i==2:
        continue
    else:
        print(f'{i} is not 2')


In [ ]:
for i in range(4):    # [0, 1, 2, 3]
    if i==2:
        break
    else:
        print(f'{i} is not 2')


In [ ]:
A = False

if A:
    print('True')
else:
    print('False')

In [ ]:
if A:
    pass
else:
    print('False')

## list comprehension v. for-loop
- 앞 리스트에서 뒤 리스트에 속한 항목 제외하기

In [ ]:
[s for s in ['KOR', 'USA', 'CHN'] if s not in ['CHN','AUS']]

In [ ]:
clist = []
for c in ['KOR', 'USA', 'CHN']:
    if c not in ['CHN', 'AUS']:
        clist = clist + [c] # clist.append(c)
clist

# 라이브러리
- Numpy: 매틀랩 대체, 과학적 연산
- Pandas: 데이터 분석
- Matplotlib: 데이터 시각화, 그래프
- os, pickle: 운영체제, 시스템과 상호작용
- Statsmodels: 통계분석
- Scikit-learn, TensorFlow: 머신러닝, AI

## numpy
- ndarray는 행(row)과 열(column) 보다 첫번째 차원, 두번째 차원, 세번째 차원 등으로 정의
- 필요한 경우 matrix 자료형을 사용할 수 있으나 활용도가 낮음
- ndarray자료형을 이용하여 일반적인 matrix연산을 모두 할 수 있음
- 2-dim ndarray에서 행(row)처럼 보이는 것은 첫번째 차원임

In [ ]:
import numpy # numpy 라이브러리 함수를 사용하려면 numpy. 으로 표현
import numpy as np # numpy. 에서 np. 으로 대체
print(numpy.sin(0), np.sin(0))

In [ ]:
print(sin(0)) # np. 로 시작하지 않기 때문에 오류

In [ ]:
print(np.pi)

## 인덱스

- 특정 열(두번째 차원)에 접근하기 위해서는 콜론(:)을 첫번째 인덱스 자리에 입력

In [185]:
a1 = np.array([[1, 2 ,3], [2, 3, 4]])

In [ ]:
a1[:, 0] # 전체 차원의 첫번째 원소

In [ ]:
a1[0, :] # 첫번째 차원의 모든 원소

## 통계량 및 연산

In [ ]:
v = np.array([1, 2, 3])
print(v)

In [ ]:
type(v)

In [ ]:
m = np.array([[1, 2], [3, 4]])
m

In [ ]:
print(v.mean(), v.std(), v.max())

In [ ]:
np.sin([0, np.pi / 2, np.pi])

In [ ]:
a = np.array([[1, 2], [3, 4]])

In [ ]:
a

array([[1, 2],
       [3, 4]])

In [ ]:
a[0,0] = -1

In [ ]:
a

In [ ]:
a[0] = 0
a

In [ ]:
a[:, 1] = [5, 6]
print(a)

In [203]:
v1 = np.array([1, 2, 3])
v2 = np.array([-1, 0, 1])

In [ ]:
v1 + 1

In [ ]:
v1 * 2

In [ ]:
v1 ** 2

In [ ]:
v1 + v2

In [ ]:
np.log(v1)

In [ ]:
np.exp(v1)

## matrix operation

- numpy array로 생성된 객체는 ndarray 클래스의 메소드와 속성을 가짐
- transpose, dot product 등

In [223]:
a2 = np.array([[1, 2], [3, 4], [5, 6]])

In [226]:
a1 * a2

ValueError: ignored

In [ ]:
a1.dot(a2)

In [ ]:
np.dot(a1, a2)

In [233]:
A = np.dot(a1, a2)
print(A)

[[22 28]
 [31 40]]


- 역행렬: numpy.linalg.inv() 함수 이용

In [ ]:
print(np.linalg.inv(a1.dot(a2)))

In [236]:
from numpy.linalg import inv

In [ ]:
inv(a1.dot(a2))

In [ ]:
np.identity(a1.shape[0])

In [230]:
from numpy import identity as eye

In [ ]:
eye(a1.shape[0])

- 레온티에프 역행렬: $(I - A)^{-1}$

In [ ]:
np.linalg.inv(np.identity(A.shape[0]) - A)

In [ ]:
inv(eye(A.shape[0]) - A)

## random sample

- 동일한 랜덤표본을 얻기 위해서는 numpy.random.seed(n) (예: n=1) 실행
    - seed()를 지정하지 않는 경우 파이썬은 현재 날짜-시간을 이용하여 seed() 지정

In [238]:
import numpy as np

In [239]:
rsn = np.random.randn(10) # 표준정규분포에서 샘플링

In [240]:
rsn

array([-1.18997876, -0.11208947, -0.62463444,  1.37361405,  0.12405343,
        0.18767963, -1.04043274,  0.22354029,  0.16219621, -1.75278601])

In [245]:
rsi = np.random.randint(1, 10, 10) # 1과 9사이에서 10개 샘플링

In [246]:
rsi

array([4, 2, 5, 3, 7, 1, 4, 8, 6, 4])

In [250]:
rsu = np.random.uniform(-1, 1, 10)

In [251]:
rsu

array([-0.29819086,  0.77404705,  0.8905813 , -0.91681308, -0.68549699,
        0.37716905,  0.4830619 ,  0.71218543, -0.77572403, -0.33535897])

In [ ]:
np.random.seed(1)
np.random.randn(3)

In [ ]:
np.random.seed(2)
np.random.randn(3)

In [ ]:
np.random.seed(1)
np.random.randn(3)

# 연습문제
1. $x + y + x*y + x ** 2$ 계산해서 return하는 함수 생성 (def)

2. 아래 a1, a2 리스트를 이용해서 a1의 요소가 key이고, a2의 요소가 value인 딕셔너리 생성( dict(), zip() )

In [255]:
a1 = ['a', 'b', 'c', 'd', 'e']
a2 = list(range(5))

3. 리스트 컴프리헨션을 이용해서 아래 a 리스트의 각 요소를 제곱한 리스트 생성

In [258]:
a = list(range(2, 10))

4. 위의 a 리스트를 ndarray 자료형으로 변환하고 제곱하시오

5. 2의 a1 리스트의 인덱스와 요소를 반복구문을 통해 print하시오 ( enumerate() )